package com.sky.ai_quiz;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;

/**
 * This file contains Java records to represent the structure of the JSON
 * sent to and received from the Google Gemini API. These act as
 * Data Transfer Objects (DTOs).
 */
public class GeminiDtos {

    // --- Request Objects ---

    /**
     * Represents the main request body sent to the Gemini API.
     */
    public record GeminiRequest(List<Content> contents, GenerationConfig generationConfig) {}

    /**
     * Represents a piece of content, which contains parts (our prompt).
     */
    public record Content(List<Part> parts) {}

    /**
     * Represents a single part of the content, holding the prompt text.
     */
    public record Part(String text) {}

    /**
     * Configuration for the generation, specifying we want a JSON response.
     */
    public record GenerationConfig(@JsonProperty("response_mime_type") String responseMimeType) {}


    // --- Response Objects ---

    /**
     * Represents the top-level response from the Gemini API.
     */
    public record GeminiResponse(List<Candidate> candidates) {}

    /**
     * Represents a single candidate solution generated by the model.
     */
    public record Candidate(Content content) {}
}
