# render.yaml - Tells Render how to deploy both services from one repository.

services:
  # -----------------
  # Spring Boot Backend Service
  # -----------------
  - type: web
    name: ai-quiz-backend
    # This is the crucial part: we explicitly tell Render this is a Java service.
    runtime: java
    # Tells Render to look inside the 'ai-quiz' folder for this service.
    rootDir: ai-quiz
    plan: free # This uses the free instance type
    # Build and start commands for a Spring Boot application.
    buildCommand: "./mvnw clean install"
    startCommand: "java -jar target/ai-quiz-0.0.1-SNAPSHOT.jar"
    envVars:
      - key: GOOGLE_API_KEY
        # IMPORTANT: This will sync from a secret you create in the Render dashboard.
        fromGroup: api-keys 

  # -----------------
  # React Frontend Service
  # -----------------
  - type: web
    name: quiz-frontend
    # Explicitly tell Render this is a Node.js service.
    runtime: node
    # Tells Render to look inside the 'quiz-frontend' folder.
    rootDir: quiz-frontend
    plan: free
    buildCommand: "npm install && npm run build"
    # The folder where Vite places the final website files.
    publishDirectory: dist
    envVars:
      - key: VITE_API_BASE_URL
        # This powerful feature automatically uses the live URL of your backend.
        value: https://${ai-quiz-backend.host}/api

